project:
  type: website
  output-dir: docs

website:
  title: "Bill Engels's Web Log"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bwengals
      - icon: linkedin
        href: https://www.linkedin.com/in/bill-engels-a5239a119/ 
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css



